### ISSUE TITLE
最新版覆盖后注册不成功

### ISSUE THREAD

**Issue by camel007** [dcncy/GemMenu-For-Mac-Crack#5]
![image](https://user-images.githubusercontent.com/4254753/128289214-72fd9e8f-1ac1-408a-90ee-8a8346c8b1ef.png)

**Comment by yidimopozhibai** [comment]
有无win版本

**Comment by fyx98628** [comment]
wins用户不配了

**Comment by W-Sword** [comment]
@Zhifeiyu 
1、作者提供了14.06版本的安装包，可以使用那个，别用最新版
2、安装后先退出gem插件，然后替换覆盖->重启插件->注册，这样应该就可以了

**Comment by dcncy** [comment]
已更新14.9.0.135版本，亲测不必注册就可以使用，各位有需要的话可以试一下。
